DEFAULT_PAGE_SIZE = 6
INGREDIENTS_AUTOCOMPLETE_LIMIT = 50
SHORTLINK_CODE_LENGTH = 6
SHORTLINK_CODE_MAX_LENGTH = 16

TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32
INGREDIENT_NAME_MAX_LENGTH = 128
MEASUREMENT_UNIT_MAX_LENGTH = 64
RECIPE_NAME_MAX_LENGTH = 256

COOKING_TIME_MIN = 1
COOKING_TIME_MAX = 32000

INGREDIENT_AMOUNT_MIN = 1
INGREDIENT_AMOUNT_MAX = 32000
