# Generated by Django 5.1.1 on 2025-10-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_favorite_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_code',
            field=models.SlugField(blank=True, max_length=16, null=True, unique=True, verbose_name='Короткий код'),
        ),
    ]
