# Generated by Django 5.1.1 on 2025-11-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_shoppingcart_options_alter_favorite_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'ordering': ('recipe', 'ingredient'), 'verbose_name': 'Ингредиент в рецепте', 'verbose_name_plural': 'Ингредиенты в рецепте'},
        ),
    ]
