"""Новое поле is_file

Revision ID: 6bccd9a969fe
Revises: 11af66b24a32
Create Date: 2025-11-18 19:38:19.555812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bccd9a969fe'
down_revision = '11af66b24a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_file', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.drop_column('is_file')

    # ### end Alembic commands ###
